<a href="https://colab.research.google.com/github/noushadkhan01/tensorflow/blob/master/RNN/google%20stock%20price%20prediction.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [0]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
%matplotlib inline

from google.colab import files
files.upload()

In [4]:
!ls

Google_Stock_Price_Test.csv  Google_Stock_Price_Train.csv  sample_data


In [38]:
train = pd.read_csv('Google_Stock_Price_Train.csv')
train.head(2)

Date    Open    High     Low   Close     Volume
0  1/3/2012  325.25  332.83  324.97  663.59  7,380,500
1  1/4/2012  331.27  333.87  329.08  666.45  5,749,400

In [39]:
train.shape

(1258, 6)

In [40]:
test = pd.read_csv('Google_Stock_Price_Test.csv')
test.head(2)

Date    Open    High     Low   Close     Volume
0  1/3/2017  778.81  789.63  775.80  786.14  1,657,300
1  1/4/2017  788.36  791.34  783.16  786.90  1,073,000

In [41]:
test.shape

(20, 6)

**We need to train on single column of training data like Open or Close or Low or High, so choose only one of them**

In [42]:
train = train.iloc[:, 1:2]
test = test.iloc[:, 1:2]
train[:2]

Open
0  325.25
1  331.27

In [43]:
test.head(1)

Open
0  778.81

wee need numpy array to train our model so get it into numpy array

In [44]:
train = train.values
test = test.values
train[:2], test[:2]

(array([[325.25],
        [331.27]]), array([[778.81],
        [788.36]]))

# Preprocessing

In [0]:
from sklearn.preprocessing import MinMaxScaler

In [0]:
train = t.copy()
test = s.copy()

In [94]:
sc = MinMaxScaler()
sc.fit(train)
train = sc.transform(train)
test = sc.transform(test)
train[:2], test[:2]

(array([[0.08581368],
        [0.09701243]]), array([[0.92955205],
        [0.94731751]]))

In [62]:
train.shape, test.shape

((1258, 1), (20, 1))

# Make Training and testing data
**its very important part because in RNN we use time stamp of 1 means we predict the price of next day on the basis of current day 
means the input data(X_train) is current day and output (y_train) is the next day data**

In [95]:
X_train = train[:-1, :]
X_train[:2]

array([[0.08581368],
       [0.09701243]])

In [64]:
X_train.shape

(1257, 1)

In [96]:
y_train = train[1:]
y_train.shape

(1257, 1)

In [59]:
test.shape

(20, 1)

In [97]:
X_train = np.reshape(X_train, (X_train.shape[0], X_train.shape[1], 1))
X_train.shape

(1257, 1, 1)

# Make RNN

In [0]:
import tensorflow as tf

In [106]:



# Part 2 - Building the RNN

# Importing the Keras libraries and packages
from keras.models import Sequential
from keras.layers import Dense
from keras.layers import LSTM
from keras.layers import Dropout

# Initialising the RNN
regressor = Sequential()

# Adding the first LSTM layer and some Dropout regularisation
regressor.add(LSTM(units = 50, return_sequences = True, input_shape = (X_train.shape[1], 1)))
regressor.add(Dropout(0.2))

# Adding a second LSTM layer and some Dropout regularisation
regressor.add(LSTM(units = 50, return_sequences = True))
regressor.add(Dropout(0.2))

# Adding a third LSTM layer and some Dropout regularisation
regressor.add(LSTM(units = 50, return_sequences = True))
regressor.add(Dropout(0.2))

# Adding a fourth LSTM layer and some Dropout regularisation
regressor.add(LSTM(units = 50))
regressor.add(Dropout(0.2))

# Adding the output layer
regressor.add(Dense(units = 1))

# Compiling the RNN
regressor.compile(optimizer = 'adam', loss = 'mean_squared_error', metrics = ['accuracy'])

# Fitting the RNN to the Training set
regressor.fit(X_train, y_train, epochs = 100, batch_size = 32)

Epoch 1/100
1257/1257 [==============================] - 6s 5ms/step - loss: 0.2188 - acc: 7.9554e-04
Epoch 2/100
1257/1257 [==============================] - 1s 852us/step - loss: 0.0563 - acc: 0.0016
Epoch 3/100
1257/1257 [==============================] - 1s 851us/step - loss: 0.0246 - acc: 0.0016
Epoch 4/100
1257/1257 [==============================] - 1s 860us/step - loss: 0.0096 - acc: 0.0016
Epoch 5/100
1257/1257 [==============================] - 1s 852us/step - loss: 0.0085 - acc: 0.0016
Epoch 6/100
1257/1257 [==============================] - 1s 859us/step - loss: 0.0067 - acc: 0.0016
Epoch 7/100
1257/1257 [==============================] - 1s 853us/step - loss: 0.0065 - acc: 0.0016
Epoch 8/100
1257/1257 [==============================] - 1s 864us/step - loss: 0.0050 - acc: 0.0016
Epoch 9/100
1257/1257 [==============================] - 1s 854us/step - loss: 0.0053 - acc: 0.0016
Epoch 10/100
1257/1257 [==============================] - 1s 856us/step - loss: 0.0044 - acc: 0.00

In [103]:
X_train[:2]

array([[[0.08581368]],

       [[0.09701243]]])

In [74]:
train = pd.read_csv('Google_Stock_Price_Train.csv', parse_dates = ['Date'])
train = train.sort_values(by = 'Date')
train.tail(2)

Date    Open    High     Low   Close     Volume
1256 2016-12-29  783.33  785.93  778.92  782.79    744,300
1257 2016-12-30  782.75  782.78  770.41  771.82  1,770,000

In [75]:
test = pd.read_csv('Google_Stock_Price_Test.csv', parse_dates = ['Date'])
test = test.sort_values(by = 'Date')
test.head(2)

Date    Open    High     Low   Close     Volume
0 2017-01-03  778.81  789.63  775.80  786.14  1,657,300
1 2017-01-04  788.36  791.34  783.16  786.90  1,073,000

In [76]:
test.tail(1)

Date    Open    High     Low   Close     Volume
19 2017-01-31  796.86  801.25  790.52  796.79  2,160,600

In [88]:
X_test = train.iloc[1256:1257, 1:2]
X_test

Open
1256  783.33

In [89]:
X_test = X_test.values
X_test

array([[783.33]])

In [90]:
X_test.shape

(1, 1)

In [91]:
X_test = np.reshape(X_test, (X_test.shape[0], X_test.shape[1], 1))
X_test.shape

(1, 1, 1)

In [110]:
X_test

array([[[783.33]]])

In [0]:
y_predict = regressor.predict(X_test)

In [112]:
y_predict

array([[-0.20455475]], dtype=float32)

In [113]:
sc.inverse_transform(y_predict)

array([[169.15955]], dtype=float32)

In [0]:
test